update pulse.alternate_care_facility
set (phone_number, city, state, zipcode) = (
        '555-' || trunc(random() * 10) || trunc(random() * 10) || trunc(random() * 10) || trunc(random() * 10)
        ,
        case
        when name like 'Alameda%' then (select city from pulse.fake_data where county = 'Alameda' order by random() limit 1)
        when name like 'Alpine%' then (select city from pulse.fake_data where county = 'Alpine' order by random() limit 1)
        when name like 'Amador%' then (select city from pulse.fake_data where county = 'Amador' order by random() limit 1)
        when name like 'Butte%' then (select city from pulse.fake_data where county = 'Butte' order by random() limit 1)
        when name like 'Calaveras%' then (select city from pulse.fake_data where county = 'Calaveras' order by random() limit 1)
        when name like 'Colusa%' then (select city from pulse.fake_data where county = 'Colusa' order by random() limit 1)
        when name like 'Contra Costa%' then (select city from pulse.fake_data where county = 'Contra Costa' order by random() limit 1)
        when name like 'Del Norte%' then (select city from pulse.fake_data where county = 'Del Norte' order by random() limit 1)
        when name like 'El Dorado%' then (select city from pulse.fake_data where county = 'El Dorado' order by random() limit 1)
        when name like 'Fresno%' then (select city from pulse.fake_data where county = 'Fresno' order by random() limit 1)
        when name like 'Glenn%' then (select city from pulse.fake_data where county = 'Glenn' order by random() limit 1)
        when name like 'Humboldt%' then (select city from pulse.fake_data where county = 'Humboldt' order by random() limit 1)
        when name like 'Imperial%' then (select city from pulse.fake_data where county = 'Imperial' order by random() limit 1)
        when name like 'Inyo%' then (select city from pulse.fake_data where county = 'Inyo' order by random() limit 1)
        when name like 'Kern%' then (select city from pulse.fake_data where county = 'Kern' order by random() limit 1)
        when name like 'Kings%' then (select city from pulse.fake_data where county = 'Kings' order by random() limit 1)
        when name like 'Lake%' then (select city from pulse.fake_data where county = 'Lake' order by random() limit 1)
        when name like 'Lassen%' then (select city from pulse.fake_data where county = 'Lassen' order by random() limit 1)
        when name like 'Los Angeles%' then (select city from pulse.fake_data where county = 'Los Angeles' order by random() limit 1)
        when name like 'Madera%' then (select city from pulse.fake_data where county = 'Madera' order by random() limit 1)
        when name like 'Marin%' then (select city from pulse.fake_data where county = 'Marin' order by random() limit 1)
        when name like 'Mariposa%' then (select city from pulse.fake_data where county = 'Mariposa' order by random() limit 1)
        when name like 'Mendocino%' then (select city from pulse.fake_data where county = 'Mendocino' order by random() limit 1)
        when name like 'Merced%' then (select city from pulse.fake_data where county = 'Merced' order by random() limit 1)
        when name like 'Modoc%' then (select city from pulse.fake_data where county = 'Modoc' order by random() limit 1)
        when name like 'Mono%' then (select city from pulse.fake_data where county = 'Mono' order by random() limit 1)
        when name like 'Monterey%' then (select city from pulse.fake_data where county = 'Monterey' order by random() limit 1)
        when name like 'Napa%' then (select city from pulse.fake_data where county = 'Napa' order by random() limit 1)
        when name like 'Nevada%' then (select city from pulse.fake_data where county = 'Nevada' order by random() limit 1)
        when name like 'Orange%' then (select city from pulse.fake_data where county = 'Orange' order by random() limit 1)
        when name like 'Placer%' then (select city from pulse.fake_data where county = 'Placer' order by random() limit 1)
        when name like 'Plumas%' then (select city from pulse.fake_data where county = 'Plumas' order by random() limit 1)
        when name like 'Riverside%' then (select city from pulse.fake_data where county = 'Riverside' order by random() limit 1)
        when name like 'Sacramento%' then (select city from pulse.fake_data where county = 'Sacramento' order by random() limit 1)
        when name like 'San Benito%' then (select city from pulse.fake_data where county = 'San Benito' order by random() limit 1)
        when name like 'San Bernardino%' then (select city from pulse.fake_data where county = 'San Bernardino' order by random() limit 1)
        when name like 'San Diego%' then (select city from pulse.fake_data where county = 'San Diego' order by random() limit 1)
        when name like 'San Francisco%' then (select city from pulse.fake_data where county = 'San Francisco' order by random() limit 1)
        when name like 'San Joaquin%' then (select city from pulse.fake_data where county = 'San Joaquin' order by random() limit 1)
        when name like 'San Luis Obispo%' then (select city from pulse.fake_data where county = 'San Luis Obispo' order by random() limit 1)
        when name like 'San Mateo%' then (select city from pulse.fake_data where county = 'San Mateo' order by random() limit 1)
        when name like 'Santa Barbara%' then (select city from pulse.fake_data where county = 'Santa Barbara' order by random() limit 1)
        when name like 'Santa Clara%' then (select city from pulse.fake_data where county = 'Santa Clara' order by random() limit 1)
        when name like 'Santa Cruz%' then (select city from pulse.fake_data where county = 'Santa Cruz' order by random() limit 1)
        when name like 'Shasta%' then (select city from pulse.fake_data where county = 'Shasta' order by random() limit 1)
        when name like 'Sierra%' then (select city from pulse.fake_data where county = 'Sierra' order by random() limit 1)
        when name like 'Siskiyou%' then (select city from pulse.fake_data where county = 'Siskiyou' order by random() limit 1)
        when name like 'Solano%' then (select city from pulse.fake_data where county = 'Solano' order by random() limit 1)
        when name like 'Sonoma%' then (select city from pulse.fake_data where county = 'Sonoma' order by random() limit 1)
        when name like 'Stanislaus%' then (select city from pulse.fake_data where county = 'Stanislaus' order by random() limit 1)
        when name like 'Sutter%' then (select city from pulse.fake_data where county = 'Sutter' order by random() limit 1)
        when name like 'Tehama%' then (select city from pulse.fake_data where county = 'Tehama' order by random() limit 1)
        when name like 'Trinity%' then (select city from pulse.fake_data where county = 'Trinity' order by random() limit 1)
        when name like 'Tulare%' then (select city from pulse.fake_data where county = 'Tulare' order by random() limit 1)
        when name like 'Tuolumne%' then (select city from pulse.fake_data where county = 'Tuolumne' order by random() limit 1)
        when name like 'Ventura%' then (select city from pulse.fake_data where county = 'Ventura' order by random() limit 1)
        when name like 'Yolo%' then (select city from pulse.fake_data where county = 'Yolo' order by random() limit 1)
        when name like 'Yuba%' then (select city from pulse.fake_data where county = 'Yuba' order by random() limit 1)
        else city
        end
        , 'CA',
        case

        when name like 'Alameda%' then (select zipcode from pulse.fake_data where county = 'Alameda' order by random() limit 1)
        when name like 'Alpine%' then (select zipcode from pulse.fake_data where county = 'Alpine' order by random() limit 1)
        when name like 'Amador%' then (select zipcode from pulse.fake_data where county = 'Amador' order by random() limit 1)
        when name like 'Butte%' then (select zipcode from pulse.fake_data where county = 'Butte' order by random() limit 1)
        when name like 'Calaveras%' then (select zipcode from pulse.fake_data where county = 'Calaveras' order by random() limit 1)
        when name like 'Colusa%' then (select zipcode from pulse.fake_data where county = 'Colusa' order by random() limit 1)
        when name like 'Contra Costa%' then (select zipcode from pulse.fake_data where county = 'Contra Costa' order by random() limit 1)
        when name like 'Del Norte%' then (select zipcode from pulse.fake_data where county = 'Del Norte' order by random() limit 1)
        when name like 'El Dorado%' then (select zipcode from pulse.fake_data where county = 'El Dorado' order by random() limit 1)
        when name like 'Fresno%' then (select zipcode from pulse.fake_data where county = 'Fresno' order by random() limit 1)
        when name like 'Glenn%' then (select zipcode from pulse.fake_data where county = 'Glenn' order by random() limit 1)
        when name like 'Humboldt%' then (select zipcode from pulse.fake_data where county = 'Humboldt' order by random() limit 1)
        when name like 'Imperial%' then (select zipcode from pulse.fake_data where county = 'Imperial' order by random() limit 1)
        when name like 'Inyo%' then (select zipcode from pulse.fake_data where county = 'Inyo' order by random() limit 1)
        when name like 'Kern%' then (select zipcode from pulse.fake_data where county = 'Kern' order by random() limit 1)
        when name like 'Kings%' then (select zipcode from pulse.fake_data where county = 'Kings' order by random() limit 1)
        when name like 'Lake%' then (select zipcode from pulse.fake_data where county = 'Lake' order by random() limit 1)
        when name like 'Lassen%' then (select zipcode from pulse.fake_data where county = 'Lassen' order by random() limit 1)
        when name like 'Los Angeles%' then (select zipcode from pulse.fake_data where county = 'Los Angeles' order by random() limit 1)
        when name like 'Madera%' then (select zipcode from pulse.fake_data where county = 'Madera' order by random() limit 1)
        when name like 'Marin%' then (select zipcode from pulse.fake_data where county = 'Marin' order by random() limit 1)
        when name like 'Mariposa%' then (select zipcode from pulse.fake_data where county = 'Mariposa' order by random() limit 1)
        when name like 'Mendocino%' then (select zipcode from pulse.fake_data where county = 'Mendocino' order by random() limit 1)
        when name like 'Merced%' then (select zipcode from pulse.fake_data where county = 'Merced' order by random() limit 1)
        when name like 'Modoc%' then (select zipcode from pulse.fake_data where county = 'Modoc' order by random() limit 1)
        when name like 'Mono%' then (select zipcode from pulse.fake_data where county = 'Mono' order by random() limit 1)
        when name like 'Monterey%' then (select zipcode from pulse.fake_data where county = 'Monterey' order by random() limit 1)
        when name like 'Napa%' then (select zipcode from pulse.fake_data where county = 'Napa' order by random() limit 1)
        when name like 'Nevada%' then (select zipcode from pulse.fake_data where county = 'Nevada' order by random() limit 1)
        when name like 'Orange%' then (select zipcode from pulse.fake_data where county = 'Orange' order by random() limit 1)
        when name like 'Placer%' then (select zipcode from pulse.fake_data where county = 'Placer' order by random() limit 1)
        when name like 'Plumas%' then (select zipcode from pulse.fake_data where county = 'Plumas' order by random() limit 1)
        when name like 'Riverside%' then (select zipcode from pulse.fake_data where county = 'Riverside' order by random() limit 1)
        when name like 'Sacramento%' then (select zipcode from pulse.fake_data where county = 'Sacramento' order by random() limit 1)
        when name like 'San Benito%' then (select zipcode from pulse.fake_data where county = 'San Benito' order by random() limit 1)
        when name like 'San Bernardino%' then (select zipcode from pulse.fake_data where county = 'San Bernardino' order by random() limit 1)
        when name like 'San Diego%' then (select zipcode from pulse.fake_data where county = 'San Diego' order by random() limit 1)
        when name like 'San Francisco%' then (select zipcode from pulse.fake_data where county = 'San Francisco' order by random() limit 1)
        when name like 'San Joaquin%' then (select zipcode from pulse.fake_data where county = 'San Joaquin' order by random() limit 1)
        when name like 'San Luis Obispo%' then (select zipcode from pulse.fake_data where county = 'San Luis Obispo' order by random() limit 1)
        when name like 'San Mateo%' then (select zipcode from pulse.fake_data where county = 'San Mateo' order by random() limit 1)
        when name like 'Santa Barbara%' then (select zipcode from pulse.fake_data where county = 'Santa Barbara' order by random() limit 1)
        when name like 'Santa Clara%' then (select zipcode from pulse.fake_data where county = 'Santa Clara' order by random() limit 1)
        when name like 'Santa Cruz%' then (select zipcode from pulse.fake_data where county = 'Santa Cruz' order by random() limit 1)
        when name like 'Shasta%' then (select zipcode from pulse.fake_data where county = 'Shasta' order by random() limit 1)
        when name like 'Sierra%' then (select zipcode from pulse.fake_data where county = 'Sierra' order by random() limit 1)
        when name like 'Siskiyou%' then (select zipcode from pulse.fake_data where county = 'Siskiyou' order by random() limit 1)
        when name like 'Solano%' then (select zipcode from pulse.fake_data where county = 'Solano' order by random() limit 1)
        when name like 'Sonoma%' then (select zipcode from pulse.fake_data where county = 'Sonoma' order by random() limit 1)
        when name like 'Stanislaus%' then (select zipcode from pulse.fake_data where county = 'Stanislaus' order by random() limit 1)
        when name like 'Sutter%' then (select zipcode from pulse.fake_data where county = 'Sutter' order by random() limit 1)
        when name like 'Tehama%' then (select zipcode from pulse.fake_data where county = 'Tehama' order by random() limit 1)
        when name like 'Trinity%' then (select zipcode from pulse.fake_data where county = 'Trinity' order by random() limit 1)
        when name like 'Tulare%' then (select zipcode from pulse.fake_data where county = 'Tulare' order by random() limit 1)
        when name like 'Tuolumne%' then (select zipcode from pulse.fake_data where county = 'Tuolumne' order by random() limit 1)
        when name like 'Ventura%' then (select zipcode from pulse.fake_data where county = 'Ventura' order by random() limit 1)
        when name like 'Yolo%' then (select zipcode from pulse.fake_data where county = 'Yolo' order by random() limit 1)
        when name like 'Yuba%' then (select zipcode from pulse.fake_data where county = 'Yuba' order by random() limit 1)
        else zipcode
        end
        )
where id = :v1;

insert into pulse.alternate_care_facility_address_line (alternate_care_facility_id, line) values
    (:v1, (select num from pulse.fake_address_num order by random() limit 1) || ' ' ||
        (select street from pulse.fake_address_street order by random() limit 1) || ' ' ||
        (select suff from pulse.fake_address_suff order by random() limit 1));
